# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yann-nginx
  namespace: nginx-ns
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: nginx:{{ .Values.nginxVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

