#pp templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    role: web
    release: {{ .Release.Name }}-release
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: web
      release: {{ .Release.Name }}-release
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: web
        release: {{ .Release.Name }}-release
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: nginx:{{ .Values.nginxVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }} 
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: APP_NAME
              value: "{{ .Values.replicaCount}}"            
            {{- range $key, $value := .Values.env}}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
