#pp templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    role: web
    release: {{ .Release.Name }}-release
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: web
      release: {{ .Release.Name }}-release
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: web
        release: {{ .Release.Name }}-release
    spec:
      containers:
        - name: {{ .Release.Name }}-container
          image: nginx:{{ .Values.nginxVersion }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: KEY1
              value: value1
            - name: KEY2
              value: value2
            - name: ANOTHER_KEY
              value: another_value
